### ISSUE TITLE
Consider setting meta rather than linkage data when no link or meta defined in relationship.

### ISSUE THREAD

**Issue by beauby** [jsonapi-rb/serializable#25]
# Current behavior
When no `link` nor `meta` was defined for a relationship, the current behavior is to include the linkage data (`data` key) in the serialized relationship, **even if that relationship was not requested via `include`** in order not to break the spec (which requires at least one of those three keys to be present).

# Issue
This behavior can be surprising and adds little value. 

# Suggested solution
When relationship is not requested and no `link` nor `meta` is defined for the relationship, fall back to including `meta: { relationship_available: false }` instead.

This is a trivial modification of [this method](https://github.com/jsonapi-rb/serializable/blob/master/lib/jsonapi/serializable/relationship.rb#L16):
```ruby
      def as_jsonapi(included)
        {}.tap do |hash|
          hash[:links] = @_links if @_links.any?
          hash[:meta]  = @_meta  unless @_meta.nil?
          include_linkage = included || (!@_links.any? && @_meta.nil?)
          hash[:data] = linkage_data if include_linkage
        end
      end
```

**Comment by richmolj** [comment]
Agree with the premise - `relationship_available` might not be the best terminology though. It's certainly *available* it just wasn't *requested*. I am thinking maybe `{ loaded: false }`, which I think is an improvement, though I'm not wild about it.

**Comment by beauby** [comment]
@richmolj Right – naming is totally up for debate, I put `relationship_available: false` as an example.

**Comment by cristianriano** [comment]
So after this, is not possible anymore to render a relationship only with the linkage data avoiding the `included` key on the document root?

**Comment by beauby** [comment]
@cristianriano It is still possible:
```ruby
has_many :posts do
  linkage always: true
end
```
